"""
singapore_corpus.py - Bootstrap official Singapore transport and AV RAG sources.
"""

from __future__ import annotations

import argparse
import json
import logging
import re
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Any, Literal

import httpx
from dotenv import load_dotenv

from skymirror.tools.rag_ingest import _read_int_env, ingest_namespace

logger = logging.getLogger(__name__)

load_dotenv()

_DEFAULT_DOWNLOAD_ROOT = Path("data/sources/singapore-official")
_DEFAULT_RAG_ROOT = Path("data/rag")
_DEFAULT_HTTP_TIMEOUT_SECONDS = 60
_USER_AGENT = "SkyMirrorRAGBootstrap/0.1 (+https://www.lta.gov.sg/)"


@dataclass(frozen=True)
class CuratedSource:
    slug: str
    title: str
    kind: Literal["pdf", "html", "note"]
    namespaces: tuple[str, ...]
    url: str | None = None
    notes: str = ""
    note_body: str = ""


_CURATED_SOURCES: tuple[CuratedSource, ...] = (
    CuratedSource(
        slug="tr68_part1_basic_behaviour",
        title="TR 68-1:2021 Autonomous vehicles - Part 1 : Basic behaviour",
        kind="html",
        url="https://www.singaporestandardseshop.sg/Product/SSPdtDetail/e7c32178-6b0f-4ea7-a5bd-951e41eb1c6e",
        namespaces=("traffic-regulations",),
        notes=(
            "Official public overview page. The complete standard is sold separately on the "
            "Singapore Standards e-shop."
        ),
    ),
    CuratedSource(
        slug="tr68_part2_safety",
        title="TR 68-2:2021 Autonomous vehicles - Part 2 : Safety",
        kind="html",
        url="https://www.singaporestandardseshop.sg/Product/SSPdtDetail/e6e16ff8-e737-4f2c-b290-91667bb6fa37",
        namespaces=("traffic-regulations", "safety-incidents"),
        notes=(
            "Official public overview page. The complete standard is sold separately on the "
            "Singapore Standards e-shop."
        ),
    ),
    CuratedSource(
        slug="tr68_part3_cybersecurity",
        title=(
            "TR 68-3:2021 Autonomous vehicles - Part 3 : Cybersecurity principles "
            "and assessment framework"
        ),
        kind="html",
        url="https://www.singaporestandardseshop.sg/Product/SSPdtDetail/31188da9-c490-4a78-83e7-13575e8a468d",
        namespaces=("traffic-regulations",),
        notes=(
            "Official public overview page. The complete standard is sold separately on the "
            "Singapore Standards e-shop."
        ),
    ),
    CuratedSource(
        slug="tr68_part4_data_formats",
        title="TR 68-4:2021 Autonomous vehicles - Part 4 : Vehicular data types and formats",
        kind="html",
        url="https://www.singaporestandardseshop.sg/Product/SSPdtDetail/9ecade1a-969d-471b-a8bb-1bc390641cfe",
        namespaces=("traffic-regulations", "road-conditions"),
        notes=(
            "Official public overview page. The complete standard is sold separately on the "
            "Singapore Standards e-shop."
        ),
    ),
    CuratedSource(
        slug="av_assessment_framework",
        title="LTA Autonomous Vehicles guidance and assessment framework",
        kind="html",
        url="https://www.lta.gov.sg/content/ltagov/en/industry_innovations/technologies/autonomous_vehicles.html",
        namespaces=("traffic-regulations", "safety-incidents"),
        notes=(
            "Official LTA guidance page covering trial requirements, assessment "
            "tracks, and public-path rules."
        ),
    ),
    CuratedSource(
        slug="av_application_form_public_roads_2025",
        title="Application for Trial of Autonomous Motor Vehicles (AVs) for Public Road Operations",
        kind="pdf",
        url="https://www.lta.gov.sg/content/dam/ltagov/industry_innovations/Technologies/PDF/av_application_20250114.pdf",
        namespaces=("traffic-regulations", "safety-incidents"),
        notes="Official LTA application form dated 14 January 2025.",
    ),
    CuratedSource(
        slug="as01_public_access_note",
        title="AS 01 public-access note",
        kind="note",
        namespaces=("traffic-regulations",),
        notes="Acquisition note generated by the bootstrapper.",
        note_body=(
            "A public AS 01 download URL was not located during corpus bootstrap "
            "setup on 2026-04-14.\n\n"
            "Use the official LTA Autonomous Vehicles guidance page and the 2025 "
            "public-road AV application form as the public substitute corpus until a "
            "licensed AS 01 copy is available.\n\n"
            "If you obtain a licensed AS 01 document, place a text-extractable copy under "
            "`data/rag/traffic-regulations/` and rerun `skymirror-rag-ingest`."
        ),
    ),
    CuratedSource(
        slug="smart_mobility_2030",
        title="Smart Mobility 2030",
        kind="pdf",
        url="https://www.lta.gov.sg/content/dam/ltagov/getting_around/driving_in_singapore/intelligent_transport_systems/pdf/smartmobility2030.pdf",
        namespaces=("traffic-regulations", "road-conditions"),
        notes=(
            "Official LTA and ITS Singapore master plan PDF referenced from the "
            "Intelligent Transport Systems page."
        ),
    ),
    CuratedSource(
        slug="sdre_revision_i_mar_2026",
        title="Standard Details of Road Elements (Revision I - MAR 2026)",
        kind="pdf",
        url="https://www.lta.gov.sg/content/dam/ltagov/industry_innovations/industry_matters/development_construction_resources/Street_Work_Proposals/Standards_and_Specifications/SDRE/Content_Page_March_2026.pdf",
        namespaces=("road-conditions",),
        notes="Official LTA SDRE revision published for effect from 1 June 2026.",
    ),
    CuratedSource(
        slug="traffic_control_at_work_zone_july_2019",
        title="Code of Practice for Traffic Control at Work Zone (July 2019 Edition)",
        kind="pdf",
        url="https://www.lta.gov.sg/content/dam/ltagov/industry_innovations/industry_matters/development_construction_resources/Street_Work_Proposals/codes_of_practice/COP_Traffic_Control_at_Work_Zone_July_2019_Edition.pdf",
        namespaces=("safety-incidents", "road-conditions"),
        notes="Official LTA work-zone traffic control code of practice PDF.",
    ),
    CuratedSource(
        slug="datamall_api_user_guide",
        title="LTA DataMall API User Guide",
        kind="pdf",
        url="https://datamall.lta.gov.sg/content/dam/datamall/datasets/LTA_DataMall_API_User_Guide.pdf",
        namespaces=("traffic-regulations", "road-conditions"),
        notes="Official DataMall API documentation PDF.",
    ),
    CuratedSource(
        slug="datamall_gis_user_guide",
        title="LTA DataMall GIS User Guide",
        kind="pdf",
        url="https://datamall.lta.gov.sg/content/dam/datamall/datasets/LTA_DataMall_GIS_User_Guide.pdf",
        namespaces=("road-conditions",),
        notes="Official DataMall geospatial documentation PDF.",
    ),
    CuratedSource(
        slug="onemap_home",
        title="OneMap home",
        kind="html",
        url="https://www.onemap.gov.sg/home/",
        namespaces=("road-conditions",),
        notes="Official Singapore Land Authority overview page for OneMap and the OneMap API.",
    ),
    CuratedSource(
        slug="onemap_basemap_docs",
        title="OneMap basemap documentation",
        kind="html",
        url="https://www.onemap.gov.sg/docs/maps/",
        namespaces=("road-conditions",),
        notes="Official OneMap basemap documentation page.",
    ),
    CuratedSource(
        slug="onemap_api_workshop_demo_2025",
        title="OneMap API Workshop Demo 260825",
        kind="pdf",
        url="https://www.onemap.gov.sg/apidocs/static/media/OneMap_API_Workshop_Demo_260825.6522ddef4affd370a81a.pdf",
        namespaces=("road-conditions",),
        notes="Official OneMap API workshop deck served from the OneMap API docs portal.",
    ),
    CuratedSource(
        slug="lta_annual_report_2024_2025",
        title="LTA Annual Report 2024/25",
        kind="pdf",
        url="https://www.lta.gov.sg/content/dam/ltagov/who_we_are/statistics_and_publications/report/pdf/LTA%20AR2024_25%20PDFa%20%28web%29.pdf",
        namespaces=("traffic-regulations",),
        notes="Official LTA annual report PDF for FY2024/25.",
    ),
)


def _normalise_whitespace(text: str) -> str:
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    lines = [re.sub(r"[ \t]+", " ", line).strip() for line in text.splitlines()]
    compact_lines: list[str] = []
    previous_blank = False
    for line in lines:
        if not line:
            if not previous_blank:
                compact_lines.append("")
            previous_blank = True
            continue
        compact_lines.append(line)
        previous_blank = False
    return "\n".join(compact_lines).strip()


def _extract_pdf_text(raw_path: Path) -> str:
    from pypdf import PdfReader

    reader = PdfReader(str(raw_path))
    sections: list[str] = []
    for page_number, page in enumerate(reader.pages, start=1):
        page_text = _normalise_whitespace(page.extract_text() or "")
        if not page_text:
            continue
        sections.append(f"## Page {page_number}\n\n{page_text}")
    return "\n\n".join(sections)


def _extract_html_text(raw_path: Path) -> str:
    from bs4 import BeautifulSoup

    soup = BeautifulSoup(raw_path.read_text(encoding="utf-8"), "html.parser")
    for tag_name in ("script", "style", "noscript", "svg"):
        for element in soup.find_all(tag_name):
            element.decompose()

    root = soup.find("main") or soup.find("body") or soup
    text = root.get_text("\n")
    return _normalise_whitespace(text)


def _render_markdown(
    source: CuratedSource,
    *,
    retrieved_at: str,
    raw_path: Path | None,
    body: str,
) -> str:
    lines = [f"# {source.title}", ""]
    if source.url:
        lines.append(f"- Source URL: {source.url}")
    lines.append(f"- Retrieved At: {retrieved_at}")
    lines.append(f"- Source Type: {source.kind}")
    if raw_path is not None:
        lines.append(f"- Raw File: {raw_path.as_posix()}")
    if source.notes:
        lines.append(f"- Notes: {source.notes}")
    lines.extend(["", body.strip(), ""])
    return "\n".join(lines)


def _raw_suffix_for_source(source: CuratedSource) -> str:
    if source.kind == "pdf":
        return ".pdf"
    if source.kind == "html":
        return ".html"
    return ".md"


def _download_source(
    source: CuratedSource, client: httpx.Client, raw_dir: Path, force: bool
) -> Path:
    if source.url is None:
        raise ValueError(f"Source '{source.slug}' does not define a URL.")

    raw_dir.mkdir(parents=True, exist_ok=True)
    raw_path = raw_dir / f"{source.slug}{_raw_suffix_for_source(source)}"
    if raw_path.exists() and not force:
        return raw_path

    response = client.get(source.url)
    response.raise_for_status()
    raw_path.write_bytes(response.content)
    return raw_path


def _render_note_source(source: CuratedSource, rag_dir: Path) -> list[Path]:
    if not source.note_body.strip():
        raise ValueError(f"Note source '{source.slug}' is missing note_body.")

    retrieved_at = datetime.now(UTC).isoformat()
    markdown = _render_markdown(
        source,
        retrieved_at=retrieved_at,
        raw_path=None,
        body=source.note_body,
    )
    output_paths: list[Path] = []
    for namespace in source.namespaces:
        namespace_dir = rag_dir / namespace
        namespace_dir.mkdir(parents=True, exist_ok=True)
        output_path = namespace_dir / f"{source.slug}.md"
        output_path.write_text(markdown, encoding="utf-8")
        output_paths.append(output_path)
    return output_paths


def _materialize_source(
    source: CuratedSource,
    *,
    client: httpx.Client | None,
    raw_dir: Path,
    rag_dir: Path,
    force: bool,
) -> dict[str, Any]:
    if source.kind == "note":
        rag_paths = _render_note_source(source, rag_dir)
        return {
            "slug": source.slug,
            "title": source.title,
            "status": "rendered_note",
            "url": source.url,
            "raw_path": None,
            "rag_paths": [path.as_posix() for path in rag_paths],
        }

    if client is None:
        raise ValueError("A HTTP client is required for downloadable sources.")

    retrieved_at = datetime.now(UTC).isoformat()
    raw_path = _download_source(source, client, raw_dir, force)

    if source.kind == "pdf":
        body = _extract_pdf_text(raw_path)
    else:
        body = _extract_html_text(raw_path)

    markdown = _render_markdown(
        source,
        retrieved_at=retrieved_at,
        raw_path=raw_path,
        body=body or "No text could be extracted from the downloaded source.",
    )

    rag_paths: list[Path] = []
    for namespace in source.namespaces:
        namespace_dir = rag_dir / namespace
        namespace_dir.mkdir(parents=True, exist_ok=True)
        output_path = namespace_dir / f"{source.slug}.md"
        output_path.write_text(markdown, encoding="utf-8")
        rag_paths.append(output_path)

    return {
        "slug": source.slug,
        "title": source.title,
        "status": "downloaded",
        "url": source.url,
        "raw_path": raw_path.as_posix(),
        "rag_paths": [path.as_posix() for path in rag_paths],
    }


def bootstrap_singapore_corpus(
    *,
    download_root: Path,
    rag_root: Path,
    force: bool = False,
    ingest: bool = False,
    clear_first: bool = False,
) -> dict[str, Any]:
    raw_dir = download_root / "raw"
    raw_dir.mkdir(parents=True, exist_ok=True)
    rag_root.mkdir(parents=True, exist_ok=True)

    timeout_seconds = _read_int_env(
        "SINGAPORE_CORPUS_HTTP_TIMEOUT_SECONDS", _DEFAULT_HTTP_TIMEOUT_SECONDS
    )
    headers = {"User-Agent": _USER_AGENT}
    results: list[dict[str, Any]] = []
    touched_namespaces: set[str] = set()

    with httpx.Client(
        follow_redirects=True,
        headers=headers,
        timeout=httpx.Timeout(timeout_seconds),
    ) as client:
        for source in _CURATED_SOURCES:
            try:
                result = _materialize_source(
                    source,
                    client=client,
                    raw_dir=raw_dir,
                    rag_dir=rag_root,
                    force=force,
                )
                results.append(result)
                touched_namespaces.update(source.namespaces)
                logger.info("singapore_corpus: prepared %s", source.slug)
            except Exception as exc:
                logger.exception("singapore_corpus: failed to prepare %s", source.slug)
                results.append(
                    {
                        "slug": source.slug,
                        "title": source.title,
                        "status": "failed",
                        "url": source.url,
                        "error": str(exc),
                    }
                )

    manifest = {
        "generated_at": datetime.now(UTC).isoformat(),
        "download_root": download_root.as_posix(),
        "rag_root": rag_root.as_posix(),
        "results": results,
    }

    manifest_path = download_root / "manifest.json"
    manifest_path.write_text(json.dumps(manifest, ensure_ascii=True, indent=2), encoding="utf-8")

    ingested_chunks: dict[str, int] = {}
    if ingest:
        for namespace in sorted(touched_namespaces):
            namespace_dir = rag_root / namespace
            ingested_chunks[namespace] = ingest_namespace(
                namespace,
                namespace_dir,
                chunk_size=_read_int_env("RAG_CHUNK_SIZE", 1200),
                overlap=_read_int_env("RAG_CHUNK_OVERLAP", 200),
                clear_first=clear_first,
            )

    manifest["manifest_path"] = manifest_path.as_posix()
    manifest["ingested_chunks"] = ingested_chunks
    manifest_path.write_text(json.dumps(manifest, ensure_ascii=True, indent=2), encoding="utf-8")
    return manifest


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        prog="skymirror-rag-bootstrap-sg",
        description=(
            "Download, normalize, and optionally ingest official Singapore transport corpus files."
        ),
    )
    parser.add_argument(
        "--download-root",
        default=str(_DEFAULT_DOWNLOAD_ROOT),
        help="Directory where raw downloads and the manifest will be stored.",
    )
    parser.add_argument(
        "--rag-root",
        default=str(_DEFAULT_RAG_ROOT),
        help="Directory where normalized namespace markdown files will be written.",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Re-download raw sources even if cached files already exist.",
    )
    parser.add_argument(
        "--ingest",
        action="store_true",
        help="After download and normalization, ingest the generated markdown files into Pinecone.",
    )
    parser.add_argument(
        "--clear-first",
        action="store_true",
        help="When used with --ingest, clear the Pinecone namespace before upserting the corpus.",
    )
    return parser.parse_args()


def main() -> None:
    logging.basicConfig(
        level=logging.INFO, format="%(asctime)s [%(levelname)s] %(name)s: %(message)s"
    )
    args = _parse_args()
    manifest = bootstrap_singapore_corpus(
        download_root=Path(args.download_root).resolve(),
        rag_root=Path(args.rag_root).resolve(),
        force=args.force,
        ingest=args.ingest,
        clear_first=args.clear_first,
    )
    logger.info("singapore_corpus: manifest written to %s", manifest["manifest_path"])
    if manifest["ingested_chunks"]:
        logger.info("singapore_corpus: ingested chunk counts %s", manifest["ingested_chunks"])


if __name__ == "__main__":
    main()
