"""
state.py — Global State Definition for SKYMIRROR
=================================================
`SkymirrorState` is the single source of truth passed between every node in
the LangGraph pipeline. LangGraph merges partial dicts returned by each node
into this shared state object.

Reducer annotations on mutable fields (`expert_results`, `alerts`) allow safe
parallel fan-out to multiple expert nodes: each expert writes its own key/items
and LangGraph merges the results before handing control to the alert manager.
"""

from __future__ import annotations

import operator
from typing import Annotated, Any, Literal, Optional, TypedDict


# ---------------------------------------------------------------------------
# Custom Reducers
# ---------------------------------------------------------------------------

def _merge_dicts(a: dict[str, Any], b: dict[str, Any]) -> dict[str, Any]:
    """
    Merge partial dictionaries returned by parallel LangGraph branches.

    Args:
        a: Accumulated results so far.
        b: New partial results from the current node.

    Returns:
        A merged mapping containing both dictionaries.
    """
    return {**a, **b}


# ---------------------------------------------------------------------------
# Shared Schemas
# ---------------------------------------------------------------------------

SeverityLevel = Literal["low", "medium", "high", "critical"]
ConfidenceLevel = Literal["low", "medium", "high"]
ImpactScope = Literal["local", "single_lane", "multi_lane", "intersection"]
PersistenceLevel = Literal["new", "persistent", "worsening", "unknown"]


class ValidatedSignals(TypedDict, total=False):
    """Lightweight structured hints extracted by the validator."""

    vehicle_count: int
    stopped_vehicle_count: int
    pedestrian_present: bool
    blocked_lanes: int
    queueing: bool
    water_present: bool
    construction_present: bool
    obstacle_present: bool
    low_visibility: bool
    lighting_abnormal: bool
    wrong_way_cue: bool
    collision_cue: bool
    dangerous_crossing_cue: bool
    conflict_risk_cue: bool


class ExpertScenario(TypedDict):
    """One scenario detected by an expert agent."""

    name: str
    severity: SeverityLevel
    confidence: ConfidenceLevel
    reason: str
    evidence: list[str]
    impact_scope: ImpactScope
    persistence: PersistenceLevel
    recommended_actions: list[str]


class ExpertResult(TypedDict):
    """Structured output emitted by one expert agent."""

    matched: bool
    category: str
    summary: str
    urgent: bool
    scenarios: list[ExpertScenario]


class HistoryFrame(TypedDict, total=False):
    """Snapshot of a previous frame used for short-term temporal reasoning."""

    image_path: str
    validated_text: str
    validated_signals: ValidatedSignals
    expert_results: dict[str, ExpertResult]


# ---------------------------------------------------------------------------
# State Schema
# ---------------------------------------------------------------------------

class SkymirrorState(TypedDict, total=False):
    """
    Shared state object for the SKYMIRROR LangGraph pipeline.

    Fields
    ------
    image_path:
        Absolute path (or URI) of the traffic camera frame being processed.

    vlm_text:
        Raw textual description produced by the VLM agent from the image.

    validated_text:
        Refined, normalized description used by downstream routing and experts.

    validated_signals:
        Lightweight structured cues extracted from `validated_text`.

    history_context:
        Short-term in-memory history for the same camera. Used by experts to
        infer persistence and simple temporal patterns such as repeated queueing.

    active_experts:
        List of expert node names selected by the orchestrator.

    expert_results:
        Aggregated findings from activated expert agents. Each expert writes
        under its own key and the reducer merges them safely.

    alerts:
        Structured alert objects generated by the alert manager.

    metadata:
        Optional runtime diagnostics bag.
    """

    # --- Ingestion -----------------------------------------------------------
    image_path: str

    # --- Vision → Language ---------------------------------------------------
    vlm_text: str

    # --- Validation ----------------------------------------------------------
    validated_text: str
    validated_signals: ValidatedSignals
    history_context: list[HistoryFrame]

    # --- Orchestration -------------------------------------------------------
    active_experts: list[str]

    # --- Expert Analysis (parallel-safe via reducers) ------------------------
    expert_results: Annotated[dict[str, ExpertResult], _merge_dicts]
    alerts: Annotated[list[dict[str, Any]], operator.add]

    # --- Diagnostics (optional) ----------------------------------------------
    metadata: Optional[dict[str, Any]]
