"""
state.py - Global state definition for SKYMIRROR.
"""

from __future__ import annotations

import operator
from typing import Annotated, Any

from typing_extensions import TypedDict


def _merge_dicts(a: dict[str, Any], b: dict[str, Any]) -> dict[str, Any]:
    """Merge two flat dictionaries."""
    return {**a, **b}


def _deep_merge_dicts(a: dict[str, Any], b: dict[str, Any]) -> dict[str, Any]:
    """Recursively merge nested dictionaries."""
    merged: dict[str, Any] = dict(a)

    for key, value in b.items():
        existing = merged.get(key)
        if isinstance(existing, dict) and isinstance(value, dict):
            merged[key] = _deep_merge_dicts(existing, value)
        else:
            merged[key] = value

    return merged


class SkymirrorState(TypedDict, total=False):
    """
    Shared state object for the SKYMIRROR LangGraph pipeline.

    Fields
    ------
    image_path:
        Absolute path or URI of the traffic camera frame being processed.
    guardrail_result:
        Result of the image safety gate before the VLMs are invoked.
    vlm_outputs:
        Parallel-safe mapping of provider name to raw description text.
        Expected keys: `gemini`, `qwen`.
    validated_text:
        Canonical text produced by the validator after reconciling Gemini and
        Qwen outputs.
    active_experts:
        Expert node names selected by the expert router.
    expert_results:
        Aggregated downstream expert findings.
    alerts:
        Structured alert objects generated by the alert manager.
    metadata:
        Diagnostics and per-stage runtime details.
    """

    image_path: str
    guardrail_result: dict[str, Any]
    vlm_outputs: Annotated[dict[str, str], _merge_dicts]
    validated_text: str
    active_experts: list[str]
    expert_results: Annotated[dict[str, Any], _merge_dicts]
    alerts: Annotated[list[dict[str, Any]], operator.add]
    metadata: Annotated[dict[str, Any], _deep_merge_dicts]
