"""
state.py — Global State Definition for SKYMIRROR
=================================================
`SkymirrorState` is the single source of truth passed between every node in
the LangGraph pipeline.  LangGraph merges partial dicts returned by each node
into this shared state object.

Reducer annotations on mutable fields (`expert_results`, `alerts`) allow safe
parallel fan-out to multiple expert nodes: each expert writes its own key/items
and LangGraph merges the results before handing control to the alert_manager.
"""

from __future__ import annotations

import operator
from typing import Annotated, Any, Optional

from typing_extensions import TypedDict


# ---------------------------------------------------------------------------
# Custom Reducers
# ---------------------------------------------------------------------------

def _merge_dicts(a: dict[str, Any], b: dict[str, Any]) -> dict[str, Any]:
    """
    Reducer for `expert_results`.

    When multiple experts run in parallel (via LangGraph's Send API), each
    expert returns a partial dict like `{"order_expert": {...findings...}}`.
    This reducer merges those partial dicts into one unified mapping without
    clobbering existing keys.

    Args:
        a: Accumulated expert results so far.
        b: New partial expert results from the current node.

    Returns:
        Merged dict combining all expert outputs.
    """
    return {**a, **b}


# ---------------------------------------------------------------------------
# State Schema
# ---------------------------------------------------------------------------

class SkymirrorState(TypedDict, total=False):
    """
    Shared state object for the SKYMIRROR LangGraph pipeline.

    Fields
    ------
    image_path : str
        Absolute path (or URI) of the traffic camera frame being processed.
        Set once at entry; read-only for all downstream nodes.

    vlm_text : str
        Raw textual description produced by the VLM agent from the image.
        May contain noise, hallucinations, or formatting artefacts that the
        validator_agent is responsible for cleaning up.

    validated_text : str
        Refined, structured description produced by the validator_agent.
        This is the canonical text used by the orchestrator for routing and
        by expert agents for analysis.

    active_experts : list[str]
        List of expert node names that the orchestrator has selected for this
        frame (e.g. `["order_expert", "safety_expert"]`).
        Populated by `route_to_experts` in edges.py.

    expert_results : dict[str, Any]
        Aggregated findings from all activated expert agents.
        Schema per key:  `{ "<expert_name>": { "findings": [...], ... } }`

        Annotated with `_merge_dicts` so that parallel expert nodes can each
        write their own key without race conditions.

    alerts : list[dict[str, Any]]
        Structured alert objects generated by the alert_manager.
        Schema per item: `{ "severity": str, "type": str, "message": str,
                             "timestamp": str, "source_expert": str }`

        Annotated with `operator.add` (list concatenation) so that the
        alert_manager can append items without overwriting earlier ones.

    metadata : dict[str, Any]  (optional)
        Arbitrary key-value bag for runtime diagnostics, tracing IDs, camera
        location info, etc.  Not processed by any agent — purely observational.
    """

    # --- Ingestion -----------------------------------------------------------
    image_path: str

    # --- Vision → Language ---------------------------------------------------
    vlm_text: str

    # --- Validation ----------------------------------------------------------
    validated_text: str

    # --- Orchestration -------------------------------------------------------
    active_experts: list[str]

    # --- Expert Analysis (parallel-safe via reducers) ------------------------
    expert_results: Annotated[dict[str, Any], _merge_dicts]
    alerts: Annotated[list[dict[str, Any]], operator.add]

    # --- Diagnostics (optional) ----------------------------------------------
    metadata: Optional[dict[str, Any]]
